blank_issues_enabled: false
contact_links:
  - name: 💬 Start a discussion
    url: https://github.com/baichuan-inc/baichuan-7B/discussions/new
    about: Please ask and answer questions here if unsure.
